# Generated by Django 3.1.6 on 2021-02-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='team',
            field=models.CharField(default='team', max_length=40),
            preserve_default=False,
        ),
    ]
