# Generated by Django 3.1.6 on 2021-02-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='summary',
            field=models.DateTimeField(),
        ),
    ]
