# Generated by Django 3.1.6 on 2021-02-10 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0002_auto_20210209_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flowchart',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
